site_name: GNPS Documentation
pages:
    - GNPS Introduction: index.md
    - Is my data compatible with GNPS?: isgnpsright.md
    - Frequently Asked Questions: faq.md
    - Superquick Start Guide: superquickstart.md
    - Quick Start Guide: quickstart.md
    - GNPS Analysis Tools Overview: gnpsanalysisoverview.md
    - Mass Spec/Computational Background:
#        - Targeted vs Untargeted: massspecbackground/targeteduntargeted.md
#        - Tandem Mass Spectrometry (MS/MS): massspecbackground/tandemms.md
#        - Methods of Identification: massspecbackground/identification.md
#        - Method of Quantification: massspecbackground/quantification.md
        - Molecular Networking: massspecbackground/networkingtheory.md
    - Data Preparation/Upload:
        - Mass Spectrometry File Conversion: fileconversion.md
        - GNPS File Upload: fileupload.md
    - Recommended Data Analysis:
        - Molecular Networking: networking.md
        - Molecular Networking Views: networkingviews.md
        - Spectral Library Search: librarysearch.md
        - MASST Search (Mass Search Tool): masst.md
        - Result Views Navigation: resultviews.md
    - Advanced Data Analysis:
        - DEREPLICATOR: dereplicator.md
        - Feature Based Molecular Networking:
            - FBMN Workflow: featurebasedmolecularnetworking.md
            - FBMN with MZmine2 : featurebasedmolecularnetworking-with-mzmine2.md
            - FBMN with MS-DIAL: featurebasedmolecularnetworking-with-ms-dial.md
            - FBMN with XCMS3: featurebasedmolecularnetworking-with-xcms3.md
            - FBMN with OpenMS: featurebasedmolecularnetworking-with-openms.md
            - FBMN with MetaboScape: featurebasedmolecularnetworking-with-metaboscape.md
            - FBMN with Progenesis QI: featurebasedmolecularnetworking-with-progenesisQI.md
            - FBMW with Cytoscape: featurebasedmolecularnetworking-cytoscape.md
        - MS2LDA and MotifDB Substructure Discovery: ms2lda.md
        - Molecular Networking in Cytoscape: cytoscape.md
        - MolNetEnhancer: molnetenhancer.md
        - Network Annotation Propagation (NAP): nap.md
        - Reanalysis of Data User Interface (ReDU): ReDU.md
    - Spectral Libraries:
        - Browsing Reference Spectral Libraries: browselibraries.md
        - Reference Spectral Library Curation: spectrumcuration.md
        - Reference Spectral Library Batch Addition: batchupload.md
        - Downloading Reference Spectral Libraries: downloadlibraries.md
        - Open-source Method for Reference Library Generation (MSMS-Chooser): msmschooser.md
    - Public Datasets:
        - Dataset Creation/Sharing: datasets.md
        - Continuous Identification: continuousid.md
        - Molecule Explorer: moleculeexplorer.md
    - Community/Social Features:
        - User Page: user.md
    - Troubleshooting: troubleshooting.md
    - Tutorial Guides:
        - Molecular Networking - Analog Discovery in Microbial Extracts: tutorials/bacterianetworking.md
        - Feature Based Molecular Networking with MZmine2 - Microbiome Molecules in Fecal Samples in American Gut Project: tutorials/americangutmzmine.md
        - Feature Based Molecular Networking with MSDial - Microbiome Molecules in Fecal Samples in American Gut Project: tutorials/americangut-ms-dial.md
        - Feature Based Molecular Networking with Metaboscape - Coffee Analysis: tutorials/coffee-tutorial-metaboscape.md
        - Feature Based Molecular Networking analysis at GNPS: tutorials/featurebasedgnps.md
            - Data Acqusition - Thermo QExactive (v1.0): msmschooserdataacquisitionQE.md
    - Presentation Materials:
        - Logos: logos.md
    - Change Log: changelog.md
    - Contact: contact.md
    - GNPS Workshops: workshops.md
theme:
    name: material
    #name: readthedocs

    #palette:
    #    primary: 'light blue'
    #    accent: 'orange'
    #font:
    #    text: 'Roboto'
    #    code: 'Roboto Mono'

    #logo: 'img/GNPS_logo.jpg'
#theme: readthedocs
#theme:
#  name: 'rtd-dropdown'
google_analytics: ['UA-8412213-5', 'ccms-ucsd.github.io']
